[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
reef-core = { path = "./reef-core" }
reef-syntax = { path = "./reef-syntax" }
clap = { version = "4.5.47", features = [
    "derive",
] }
clap_derive = "4.5.47"
